# Generated by Django 2.2.5 on 2019-09-06 11:06

from django.db import migrations


def insert_modules(apps, schema_editor):
    Module = apps.get_model('codecool_github_api', 'Module')
    modules_list = ['PB', 'WEB', 'OOP', 'ADV']
    for shortcut in modules_list:
        new_module = Module(module=shortcut)
        new_module.save()


class Migration(migrations.Migration):
    dependencies = [
        ('codecool_github_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_modules)
    ]
